version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-TarefaN3}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Config/TarefaN3.sql:/docker-entrypoint-initdb.d/TarefaN3.sql:ro

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${MYSQL_ROOT_PASSWORD:-root}
      - DB_NAME=${MYSQL_DATABASE:-TarefaN3}
    ports:
      - "3320:80"
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - db

  chatbot:
    build:
      context: ./ChatBot
      dockerfile: Dockerfile
    ports:
      - "3310:3310"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - DB_NAME=${MYSQL_DATABASE:-TarefaN3}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    depends_on:
      - db
    volumes:
      - ./ChatBot:/app:delegated

volumes:
  db_data:
